[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons
db_host = db
db_port = 5432
db_user = freight_forwarding_user
db_password = freight_forwarding_pass_2026
data_dir = /var/lib/odoo
admin_passwd = admin
http_interface = 0.0.0.0
proxy_mode = True
